default_language_version:
  python: python3
exclude: 'node_modules'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
    args: ["--maxkb=2000"]
  - id: check-ast
  - id: check-yaml
    args: ["--unsafe"]
  - id: check-toml
  - id: check-json
  - id: check-merge-conflict
  - id: detect-private-key
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.8
  hooks:
  - id: ruff
    args: ["--fix"]
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.2
  hooks:
  - id: codespell
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
  - id: bandit
    args: ["--skip", "B101,B404,B603"]
    exclude: ^(tests/|scripts/)
